apiVersion: v1
kind: Service
metadata:
  name: mywebsitefrnd
  labels:
    app: mywebsite_1_frnt
spec:
  type: NodePort
  selector:
    app: mywebsite_1_frnt
  ports:
    - name: http
      port: 80
      nodePort: 32488
